name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_database
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y postgresql-server-dev-all gcc make

    - name: Build extension
      run: |
        make
        sudo make install

    - name: Wait for PostgreSQL to start
      run: sleep 10

    - name: Run tests
      env:
        PGUSER: postgres
        PGPASSWORD: postgres
      run: |
        psql -h localhost -d my_database -c "CREATE EXTENSION pgchy_isomorphism;"
        # Здесь добавьте команды для запуска ваших тестов
