name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_database
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false
        python-version: 3.8.12

    - name: Create conda environment
      run: conda create --name build-env gcc make postgresql-server-dev-all

    - name: Activate conda environment
      run: echo "conda activate build-env" >> $GITHUB_ENV

    - name: Build extension
      run: |
        source activate build-env
        make
        sudo make install

    - name: Wait for PostgreSQL to start
      run: sleep 10

    - name: Run tests
      env:
        PGUSER: postgres
        PGPASSWORD: postgres
      run: |
        source activate build-env
        psql -h localhost -d my_database -c "CREATE EXTENSION your_extension_name;"
