name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge
        auto-activate-base: false
        python-version: 3.8.12

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install postgresql-server-dev-14 postgresql-common liblz4-dev

    - name: Initialize conda
      run: conda init bash

    - name: Create conda environment
      run: conda create --name build-env gcc make postgresql lz4

    - name: Activate conda environment
      shell: bash -l {0}
      run: conda activate build-env

    - name: Start PostgreSQL
      shell: bash -l {0}
      run: |
        conda activate build-env
        initdb -D /tmp/pgdata
        pg_ctl -D /tmp/pgdata -l /tmp/pglog start
        sleep 10
        createuser -s postgres
        createdb my_database

    - name: Build extension
      shell: bash -l {0}
      run: |
        conda activate build-env
        make
        make install

    - name: Copy extension files
      shell: bash -l {0}
      run: |
        conda activate build-env
        cp pgchy_isomorphism.control $(pg_config --sharedir)/extension/
        cp sql/pgchy_isomorphism--1.0.sql $(pg_config --sharedir)/extension/
        cp pgchy_isomorphism.so $(pg_config --pkglibdir)

    - name: Run tests
      shell: bash -l {0}
      env:
        PGUSER: postgres
        PGPASSWORD: postgres
      run: |
        conda activate build-env
        touch ~/benchmark_results.txt
        psql -h localhost -d my_database -c "CREATE EXTENSION pgchy_isomorphism;"
        psql -h localhost -d my_database -c "SELECT run_benchmark();"

    - name: Display benchmark results
      run: cat ~/benchmark_results.txt
